# Generated by Django 4.0.3 on 2022-03-28 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subject_user_registration_std_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batchsubject', to='app.batch'),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='account_no',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='bank_branch',
            field=models.CharField(default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='bank_name',
            field=models.CharField(default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='ifsc',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='payment_balance',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='payment_status',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='total_pay',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='designationbatch', to='app.batch'),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('leave_status', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('designation_id', models.CharField(max_length=200)),
                ('leaveapprovedstatus', models.CharField(max_length=200)),
                ('leave_rejected_reason', models.CharField(max_length=300)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leaveuser', to='app.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='class_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batchclass', to='app.batch')),
            ],
        ),
    ]
