# Generated by Django 4.0.3 on 2022-03-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_batch_description_subject_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Rate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
