# Generated by Django 4.0.3 on 2022-03-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_subject_logo_progressreport_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account_no',
            field=models.CharField(default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='ifsc',
            field=models.CharField(default='', max_length=240, null=True),
        ),
    ]
