# Generated by Django 4.0.3 on 2022-03-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_payment_account_no_payment_branch_payment_ifsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
