# Generated by Django 4.0.6 on 2022-07-07 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_acntspayslip'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField()),
                ('dateofappointment', models.DateField()),
                ('employid', models.CharField(max_length=255)),
                ('payment', models.IntegerField()),
                ('des', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.designation')),
            ],
        ),
    ]
