# Generated by Django 4.0.6 on 2022-07-08 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='payment',
        ),
        migrations.AddField(
            model_name='accounts',
            name='salary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.acntspayslip'),
            preserve_default=False,
        ),
    ]
