# Generated by Django 4.0.6 on 2022-07-16 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_accounts_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.acntspayslip'),
        ),
    ]
